version: '2'
services:
  web:
    image: bizongcntt1990/laravel-web:v2.0
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    links:
      - app
  app:
    image: bizongcntt1990/laravel-app:v2.4
    volumes:
      - ./:/var/www/html
    links:
      - db
      - redis
  db:
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      -  ./data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: secret
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./storage/logs/redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
